name: flutter_list_drag_and_drop
description: A new Flutter package which handles all aspects of drag and drop inside a listView.
publish_to: "none"
homepage: https://github.com/Norbert515/flutter_list_drag_and_drop
version: 0.1.8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  # The "flutter_lints" package below contains aset of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
